config/routes.rb
Rails.application.routes.draw do
  resources :docs, only: [:index, :new, :create, :destroy]
  root "docs#index"

end

app/models/doc.rb
class Doc < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  def index
    @docs = Doc.all
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.new(resume_params)

    if @doc.save
      redirect_to docs_path, notice: "The doc #{@doc.title} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy
    redirect_to docs_path, notice:  "The docs #{@doc.title} has been deleted."
  end

private
  def resume_params
    params.require(:doc).permit(:title, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/docs/create.html.erb
<h1>Docs#create</h1>
<p>Find me in app/views/docs/create.html.erb</p>

app/views/docs/destroy.html.erb
<h1>Docs#destroy</h1>
<p>Find me in app/views/docs/destroy.html.erb</p>

app/views/docs/index.html.erb
<style type="text/css">
  #gmap_wrapper {
    height: 350px;
}

#gmap_canvas {
    width: 100%;
    height: 100%;
}
</style>
<% if !flash[:notice].blank? %>

<!-- https://github.com/ChayanSharma2015/market_place_api.git -->
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Doccument", new_doc_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Ttile</th>
      <th>Download Here</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @docs.each do |doc| %>
      <tr>
        <td><%= doc.title %></td>
        <td><%= link_to "Download Doc", doc.attachment_url %></td>
        <td><%= button_to "Delete",  doc, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure that you wish to delete #{doc.title}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="gmap_wrapper">
    <div id="gmap_canvas" class="mapping"></div>
</div>
<script type="text/javascript">
  jQuery(function($) {
    // Asynchronously load the googlemap API on webpage 
    var js = document.createElement('script');
    js.src = "//maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
    document.body.appendChild(js);
});

function initialize() {
    var gmap;
    var bounds = new google.maps.LatLngBounds();
    var mapOptions = {
        mapTypeId: 'roadmap'
    };
                    
    // Display a google map on the web page
    gmap = new google.maps.Map(document.getElementById("gmap_canvas"), mapOptions);
    gmap.setTilt(45);
        
    // Multiple location Markers
    var myLocations = [
        ['New delhi, INDIA', 28.610746852715387,77.21122741699219, 'New delhi, INDIA'],
        ['UPSC New delhi, INDIA', 28.60622574490014,77.22908020019531, 'Union Service Public New delhi, INDIA'],
        ['National Zoological Park, New Delhi India', 28.6730542, 77.3238588, 'National Zoological Park, Mathura Road, New Delhi, Delhi 110003, India'],
        ['India Gate,New delhi India',28.610295,77.230797,'India Gate,New delhi India']
    ];
    // // Setup the different icons and shadows
    // var iconURLPrefix = 'http://maps.google.com/mapfiles/ms/icons/';
    
    // var icons = [
    //   iconURLPrefix + 'red-dot.png',
    //   iconURLPrefix + 'green-dot.png',
    //   iconURLPrefix + 'blue-dot.png',
    //   iconURLPrefix + 'orange-dot.png',
    //   iconURLPrefix + 'purple-dot.png',
    //   iconURLPrefix + 'pink-dot.png',      
    //   iconURLPrefix + 'yellow-dot.png'
    // ]
    // var iconsLength = icons.length;
                        
    // Info Window Content
    var infoPopupWindowContent = [];
    var temp =''
    for( i = 0; i < myLocations.length; i++ ) {
       temp = ['<div class="info_content">' + '<h3>'+myLocations[i][0]+'</h3>' + '<p>'+myLocations[i][3]+'</p>' + '</div>'];
       infoPopupWindowContent.push(temp); 
   
  }  
    // Show multiple location markers on the google map  
    var infoPopupWindow = new google.maps.InfoWindow(), marker, i;
    
    // generate the markers & place each one on the google map  
    for( i = 0; i < myLocations.length; i++ ) {
        var position = new google.maps.LatLng(myLocations[i][1], myLocations[i][2]);
        bounds.extend(position);
        marker = new google.maps.Marker({
            position: position,
            map: gmap,
            title: myLocations[i][0]
        });
        
        // Set each location marker to a infowindow    
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infoPopupWindow.setContent(infoPopupWindowContent[i][0]);
                infoPopupWindow.open(gmap, marker);
            }
        })(marker, i));

        // Fitting Automatically center the screen
        gmap.fitBounds(bounds);
    }

    // Customize google map zoom level once fitBounds run
    var boundsListener = google.maps.event.addListener((gmap), '', function(event) {
        this.setZoom(12);
        google.maps.event.removeListener(boundsListener);
    });
    
}

</script>

app/views/docs/new.html.erb
<% if !@doc.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @doc, html: { multipart: true } do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save Doccument", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyProfile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container" style="padding-top:20px;">
<%= yield %>
</div>
</body>
</html>